FROM php:5.6.16-fpm
MAINTAINER Sicco van Sas <sicco@openstate.eu>

RUN echo 'Europe/Amsterdam' > /etc/timezone

# Use the same folder as nginx for the website files
WORKDIR /usr/share/nginx/html

# Install sSMTP
RUN apt-get update && \
    apt-get install -y ssmtp
# Configure php-fpm to use sendmail
#RUN printf '\nphp_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i\n' >> /usr/local/etc/php-fpm.conf
# INSTRUCTION: You should mount ADD ssmtp.conf /etc/ssmtp/ssmtp.conf:ro 5D

# Dependencies for several of the to be installed php extensions
#RUN apt-get update && \
#    apt-get install -y curl unzip bzip2 libssl-dev libpng-dev libc-client-dev libkrb5-dev libicu-dev libmcrypt-dev libpspell-dev libsnmp-dev libxml2-dev libtidy-dev libxslt1-dev
# Configuration of the to be installed imap php extension
#RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl

# Installation of php extensions
RUN docker-php-ext-install mbstring > /dev/null
# mysql bcmath calendar dba exif ftp gd gettext imap intl mbstring mcrypt mysqli pcntl pdo_mysql pspell shmop snmp soap sockets sysvmsg sysvsem sysvshm tidy wddx xmlrpc xsl zip


#RUN echo 'upload_max_filesize = 100M' >> /usr/local/etc/php/php.ini
#RUN echo 'post_max_size = 120M' >> /usr/local/etc/php/php.ini
# should be done through mounting php.ini with these two lines

# Debug
#RUN sed -i '/error_log = \/proc\/self\/fd\/2/a log_level = debug' /usr/local/etc/php-fpm.conf
#RUN sed -i '/access.log = \/proc\/self\/fd\/2/a php_admin_value[error_log] = /proc/self/fd/2' /usr/local/etc/php-fpm.conf
#RUN sed -i '/access.log = \/proc\/self\/fd\/2/a php_flag[display_errors] = on' /usr/local/etc/php-fpm.conf
#RUN sed -i '/access.log = \/proc\/self\/fd\/2/a php_admin_flag[log_errors] = on' /usr/local/etc/php-fpm.conf
